config/routes.rb
PlForm::Application.routes.draw do
  resources :suites

  resources :cases

  resources :projects

  devise_for :users
  get "home/index"
  root :to => 'projects#index'

end

app/models/case.rb
# Case used to record....
class Case < ActiveRecord::Base
  belongs_to :project
  belongs_to :tester_user, class_name: :User
  belongs_to :suite
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :cases
  has_many :suites
  has_many :suites_cases, through: :suites, source: :cases
end

app/models/stranger.rb
class Stranger < ActiveRecord::Base
  validates :session_id, presence: true, uniqueness: true, :length => { :minimum => 2 }
end

app/models/suite.rb
class Suite < ActiveRecord::Base
  belongs_to :project
  has_many :cases
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, uniqueness: true, :length => { :minimum => 2 }
  validates :email, uniqueness: true, :allow_blank => true

protected
  def email_required?
    false
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:name)
      where(conditions).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper

end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :signed_in_user
  before_action :set_case, only: [:show, :edit, :update, :destroy]

  # GET /cases
  def index
    @cases = Case.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /cases/1
  def show
  end

  # GET /cases/new
  def new
    @case = Case.new
  end

  # GET /cases/1/edit
  def edit
  end

  # POST /cases
  def create
    @case = Case.new(case_params)

    if @case.save
      redirect_to @case, notice: 'Case was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /cases/1
  def update
    if @case.update(case_params)
      redirect_to @case, notice: 'Case was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /cases/1
  def destroy
    @case.destroy
    redirect_to cases_url, notice: 'Case was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case
      @case = Case.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def case_params
      params.require(:case).permit(:project_id, :case_name, :description, :tester_user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user.present?
  		@greeting = "#{current_user.name} 谢谢你登陆了我们网站！你已经登陆了#{current_user.sign_in_count}次了，总共登陆时间是#{stay_minutes current_user}分钟了。"
  	else
  		@greeting = "你好，陌生人！你没有登陆，或者你还没有注册，但是你已经浏览这个页面#{stay_minutes @stranger}分钟了。"
  	end
  	@stat = "现在总共有#{total_user_online_number}个注册用户在查看这个网站，有#{total_stranger_online_number}个陌生人在查看这个网站。"
  end

  def record_stay_time
    stay_sec = params[:stay_seconds].to_i
  	if current_user.present?
  		current_user.stay_seconds += stay_sec
  		current_user.save
  	else
  		@stranger = Stranger.find_or_create_by(session_id: session['session_id'])
  		@stranger.stay_seconds += stay_sec
  		@stranger.save
  	end

    respond_to do |format|
        format.json { head :no_content }
    end
  end

  def stay_time

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :signed_in_user
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /projects/1
  def show
    @new_suite = Suite.new(project_id: @project.id)# @project.suites.build
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.includes(cases: :tester_user, suites: {cases: :tester_user}).find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:project_name, :description, :start_date)
    end
end

app/controllers/suites_controller.rb
class SuitesController < ApplicationController
  before_action :signed_in_user
  before_action :set_suite, only: [:show, :edit, :update, :destroy]

  # GET /suites
  def index
    @suites = Suite.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /suites/1
  def show
  end

  # GET /suites/new
  def new
    @suite = Suite.new
  end

  # GET /suites/1/edit
  def edit
  end

  # POST /suites
  def create
    @suite = Suite.new(suite_params)

    if @suite.save
      redirect_to @suite.project, alert: 'Suite was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /suites/1
  def update
    if @suite.update(suite_params)
      redirect_to @suite, notice: 'Suite was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /suites/1
  def destroy
    @suite.destroy
    redirect_to suites_url, notice: 'Suite was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suite
      @suite = Suite.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def suite_params
      params.require(:suite).permit(:project_id, :suite_name, :description, :case_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in_user
    store_location
    redirect_to new_user_session_path, notice: 'Please sign in.' unless signed_in?
  end

  def store_location
    session[:return_to] = request.fullpath if request.get?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/cases/_form.html.erb
<%= form_for(@case) do |f| %>
  <% if @case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

      <ul>
      <% @case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :case_name %><br>
    <%= f.text_field :case_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :tester_user_id %><br>
    <%= f.text_field :tester_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cases/edit.html.erb
<h1>Editing case</h1>

<%= render 'form' %>

<%= link_to 'Show', @case %> |
<%= link_to 'Back', cases_path %>

app/views/cases/index.html.erb
<h3>Listing cases</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Project</th>
      <th>Case name</th>
      <th>Description</th>
      <th>Tester user</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cases.each do |case| %>
      <tr>
        <td><%= case.project %></td>
        <td><%= case.case_name %></td>
        <td><%= case.description %></td>
        <td><%= case.tester_user %></td>
        <td><%= link_to 'Show', case %></td>
        <td><%= link_to 'Edit', edit_case_path(case) %></td>
        <td><%= link_to 'Destroy', case, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @cases %>
<br>

<%= link_to 'New Case', new_case_path %>

app/views/cases/new.html.erb
<h1>New case</h1>

<%= render 'form' %>

<%= link_to 'Back', cases_path %>

app/views/cases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @case.project %>
</p>

<p>
  <strong>Case name:</strong>
  <%= @case.case_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @case.description %>
</p>

<p>
  <strong>Tester user:</strong>
  <%= @case.tester_user %>
</p>

<%= link_to 'Edit', edit_case_path(@case) %> |
<%= link_to 'Back', cases_path %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h3><%= @greeting %></h3>
  <h4><%= @stat %></h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bootstrap Project Startup Site</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag 'html5shiv.js' %>
    <%= javascript_include_tag 'respond.min.js' %>
  <![endif]-->
</head>
<body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
<% if Rails.env == 'development' and request.host == 'localhost' %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reference <b class="caret"></b></a>
              <ul class="dropdown-menu">
<li><a href="http://getbootstrap.com/getting-started" target="_black">Bootstrap reference</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Rails</li>
<li><a href="http://guides.rubyonrails.org/" target="_black">Rails Guides</a></li>
<li><a href="http://api.rubyonrails.org/" target="_black">Rails API</a></li>
<li><a href="http://www.ruby-doc.org/core/" target="_black">Ruby core</a></li>
<li><a href="http://www.ruby-doc.org/stdlib/" target="_black">Ruby standard library</a></li>
<li><a href="http://apidock.com/rails" target="_black">Rails API dock</a></li>
              </ul>
            </li>
<% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
<% if user_signed_in? -%>
            <li class="dropdown">
            <%= link_to edit_user_registration_path, class: 'dropdown-toggle', data: { toggle: "dropdown" } do -%>
<%= current_user.badge %><b class="caret"></b>
            <% end -%>
              <ul class="dropdown-menu">
<li><%= link_to 'Profile', edit_user_registration_path %></li>
<li class="divider"></li>
<li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
<% else -%>
<li><%= link_to 'Sign In', new_user_session_path, class: :active %></li>
<li><%= link_to 'Register', new_user_registration_path, class: :active %></li>
<% end -%>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container">
      <div class="row">
      <% if notice.present? %>
        <div class="col-md-8 col-md-offset-2">
        <div class="alert alert-info">
          <button class="close" data-dismiss="alert">×</button>
          <%= notice %>
        </div>
        </div>
      <% end %>
      <% if alert.present? %>
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Alert</h4>
      </div>
      <div class="modal-body">
        <p><%= alert %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
      <% end %>
      </div><!--/row-->
    </div><!--/.container-->
    <div class="container">
      <div class="row">
      <%= yield %>
      </div><!--/row-->
      <hr>
      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div><!--/.container-->
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_name %><br>
    <%= f.text_field :project_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h3>Listing projects</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Project name</th>
      <th>Description</th>
      <th>Start date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.project_name %></td>
        <td><%= project.description %></td>
        <td><%= project.start_date %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @projects %>
<br>

<%= link_to 'New Project', new_project_path, class: 'btn btn-primary' %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project name:</strong>
  <%= @project.project_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Suite Name</th>
      <th>Case Name</th>
      <th>Description</th>
      <th>Tester</th>
    </tr>
  </thead>

  <tbody>
    <% @project.cases.each do |c| -%>
      <tr>
        <td></td>
        <td><%= c.case_name %></td>
        <td><%= c.description %></td>
        <td><%= c.tester_user.badge %></td>
      </tr>
    <% end -%>
    <% @project.suites.each do |suite| -%>
      <% if suite.present? && suite.cases.blank? -%>
        <tr>
          <td><%= suite.suite_name %></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>
      <% suite.cases do |c| %>
        <tr>
          <td><%= suite.suite_name %></td>
          <td><%= c.case_name %></td>
          <td><%= c.description %></td>
          <td><%= c.tester_user.badge %></td>
        </tr>
      <% end -%>
    <% end -%>
  </tbody>
</table>

<%= form_for(@new_suite) do |f| %>
  <%= f.hidden_field :project_id -%>
  <div class="field">
    <%= f.label :suite_name %><br>
    <%= f.text_field :suite_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/suites/_form.html.erb
<%= form_for(@suite) do |f| %>
  <% if @suite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suite.errors.count, "error") %> prohibited this suite from being saved:</h2>

      <ul>
      <% @suite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project %><br>
    <%= f.select :project_id, Project.all.pluck(:project_name, :id) -%>
  </div>
  <div class="field">
    <%= f.label :suite_name %><br>
    <%= f.text_field :suite_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suites/edit.html.erb
<h1>Editing suite</h1>

<%= render 'form' %>

<%= link_to 'Show', @suite %> |
<%= link_to 'Back', suites_path %>

app/views/suites/index.html.erb
<h3>Listing suites</h3>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Suite name</th>
      <th>Belongs to Project</th>
      <th>Description</th>
      <th>Cases</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @suites.each do |suite| %>
      <tr>
        <td><%= suite.suite_name %></td>
        <td><%= suite.project.project_name %></td>
        <td><%= suite.description %></td>
        <td><%= suite.cases.map(&:case_name).join ', ' %></td>
        <td><%= link_to 'Show', suite %></td>
        <td><%= link_to 'Edit', edit_suite_path(suite) %></td>
        <td><%= link_to 'Destroy', suite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @suites %>
<br>

<%= link_to 'New Suite', new_suite_path %>

app/views/suites/new.html.erb
<h1>New suite</h1>

<%= render 'form' %>

<%= link_to 'Back', suites_path %>

app/views/suites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Suite name:</strong>
  <%= @suite.suite_name %>
</p>

<p>
  <strong>Belongs to Project:</strong>
  <%= @suite.project %>
</p>

<p>
  <strong>Description:</strong>
  <%= @suite.description %>
</p>

<%= link_to 'Edit', edit_suite_path(@suite) %> |
<%= link_to 'Back', suites_path %>